admins: []
forwards:
- source: -1001597526961
  dest:
  - -1001772822953
  offset: 1
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      regex: true
