admins: []
forwards:
- source: -1001757762820
  dest:
  - -1001393423202
  offset: 5424
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      regex: true
