admins: []
forwards:
- source: -100
  dest:
  - -100
  - -100
  offset: 1
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      regex: true
